"""Added description to Startup

Revision ID: fc37bec96e62
Revises: 0e3a7624b793
Create Date: 2025-02-27 14:13:12.449679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc37bec96e62'
down_revision: Union[str, None] = '0e3a7624b793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('startups', sa.Column('description', sa.String(), nullable=False))
    op.add_column('startups', sa.Column('impact_score', sa.Integer(), nullable=False))
    op.alter_column('startups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_startups_name', table_name='startups')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_startups_name', 'startups', ['name'], unique=False)
    op.alter_column('startups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('startups', 'impact_score')
    op.drop_column('startups', 'description')
    # ### end Alembic commands ###
